### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by rboy1**
`send()` and not `sent()` for response status

### CODE REVIEW

**Review by FreeMasen — APPROVED** [review]

**Comment by FreeMasen** [comment]
Thank you for the fix!

**Comment by rboy1** [comment]
> Thank you for the fix!

Most welcome. On a related note, I’m trying to use this with SmartThings, if I use the EDGE version of luxure  `response:status(200):send()` it fails with 500 http error (something about trying to call a number as a function in returned in the http response). If I try using the GitHub luxure with cosock asyncify it, it fails with some socket error. Any ideas?

**Comment by FreeMasen** [comment]
Yeah, sorry it looks like there is a bit of a disconnect between the source here and the one published on the hub. The method there seems to be `set_status`, I'll have to look into why they are different

**Comment by rboy1** [comment]
Thanks. I also noticed that in the edge library sources the response.lua file is missing

**Comment by FreeMasen** [comment]
`response.lua` is part of the [`luncheon` project](https://github.com/cosock/luncheon)

I also just realized this PR was made against my personal fork of the project, the primary source is [here](https://github.com/cosock/luxure)

**Comment by rboy1** [comment]
Before I push it, just wanted to confirm the `response:status(200)` is a supported and it's not `response:set_status(200)`. I couldn't find the method for `status` but I did see `set_status` in luncheon.

**Comment by rboy1** [comment]
I can confirm that `set_status(200)` does work with EDGE but `status(200)` returns a 500 error.

**Pull request merged**
